### ISSUE TITLE
Error in console for all websites about could not establish a connection

### ISSUE THREAD

**Issue by stokescomp** [SideeX/sideex#1]
I see this error in the dev tools console for any webpage that I go to. As soon as I disable SideeX it goes away. Some pages show it multiple times when ever ajax calls are made.
Here is the error I see:
Uncaught in promise: Could not establish connection. Receiving end does not exist. from browser-polyfill.js line 588.
At: chrome-extension://nefadabeoagfkgmkgegmjgdhegbllple/browser-polyfill.js

Here is where the error is:
```
const makeCallback = promise => {
        return (...callbackArgs) => {
          if (chrome.runtime.lastError) {
            promise.reject(chrome.runtime.lastError);
          } else if (callbackArgs.length === 1) {
            promise.resolve(callbackArgs[0]); //This is the line it is complaining about.
          } else {
            promise.resolve(callbackArgs);
          }
        };
      };
```

**Comment by petermouse** [comment]
Hi! @stokescomp 

Thank you for reporting this! 
It seems like message from content scripts to a non-existing panel will cause error.
So I let error been caught first, preventing from making annoying messages. 
 
Fixed in [1a9ebef](https://github.com/SideeX/sideex/commit/1a9ebefeb98a97239bc5c1a071930bd04cc76ab3) and also in [f24a930](https://github.com/SideeX/sideex/commit/f24a930035510a3e79d9a604b0f0e6b6e32902d5) to prevent continuous recording.
We will update it in next version.
